name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Obter o c√≥digo do projeto
      uses: actions/checkout@v4
    - name: Autenticar no Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Construir e enviar a imagem Docker
      uses: docker/build-push-action@v6
      with:
        context: ./src
        push: true
        file: ./src/Dockerfile
        tags: |
          rpsavastano/fake-shop:latest
          rpsavastano/fake-shop:v${{ github.run_number }}
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
    - name: Autenticar na AWS
      run: echo "Executando o comando aws configure"
    - name: Configurar o Kubeconfig
      run: echo "Executando o comando aws pks update kubeconfig"
    - name: Aplicar os manifestos no Kubernetes
      run: echo "Executando o comando kubectl apply"
